version: "3.9"

services:
  company_service:
    build: .
    container_name: company_service
    env_file:
      - .env.docker
    ports:
      - "8003:8003"
    depends_on:
      - db
    networks:
      - company_network

  db:
    image: postgres:15
    container_name: company_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: companydb
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - company_network
 
volumes:
  postgres_data:
 
networks:
  company_network:
